dependencies:
  - smartcontractkit/chainlink@1.1.1

compiler:
  solc:
    remappings:
      - "@chainlink=smartcontractkit/chainlink@1.1.1"

dotenv: .env

networks:
  rinkeby:
    eth_usd_price_feed: "0x8A753747A1Fa494EC906cE90E9f37563A8AF630e"

wallets:
  from_key: ${PRIVATE_KEY}
